data = [
    {
        "number": 1,
        "phrase": "Welcome to the real world. It sucks. You're gonna love it.",
        "name": "Monica",
        "season": 1 ,
        "episode": 1,
        "episode_name": "The One Where Monica Gets a Roommate",
    },
    {
        "number": 2,
        "phrase": "Not just clean, 'Monica clean.",
        "name": "Monica",
        "season":1 ,
        "episode": 6,
        "episode_name": "The One With the Butt",
    },
    {
        "number": 3,
        "phrase": "And remember: If I am harsh with you, it's only because you're doing it wrong.",
        "name": "Monica",
        "season":10 ,
        "episode": 16,
        "episode_name": "The One with Rachel's Going Away Party",
    },
    {
        "number": 4,
        "phrase": "I’m not someone who goes after a guy five minutes after he’s divorced.",
        "name": "Rachel",
        "season":5 ,
        "episode": 7,
        "episode_name": "The One Where Ross Moves In",
    },
    {
        "number": 5,
        "phrase": "No, you go after them five minutes before they get married.",
        "name": "Monica",
        "season":5 ,
        "episode": 7,
        "episode_name": "The One Where Ross Moves In",
    },
    {
        "number": 6,
        "phrase": "You can't fire me. I make your decisions and I say, 'I'm not fired.' Ha.",
        "name": "Monica",
        "season":5 ,
        "episode": 2,
        "episode_name": "The One with All the Kissing",
    },
    {
        "number": 7,
        "phrase": "Guys can fake it? Unbelievable! The one thing that's ours!",
        "name": "Monica",
        "season":9 ,
        "episode": 11,
        "episode_name": "The One Where Rachel Goes Back to Work",
    },
    {
        "number": 8,
        "phrase": "Is it me? Is it like I have a beacon that only dogs and men with severe emotional problems can hear?",
        "name": "Monica",
        "season":1 ,
        "episode": 1,
        "episode_name": "The One Where Monica Gets a Roommate",
    },
    {
        "number": 9,
        "phrase": "Go tell him he's cute. What's the worst that could happen?",
        "name": "Rachel",
        "season":2 ,
        "episode": 12,
        "episode_name": "The One After the Superbowl",
    },
    {
        "number": 10,
        "phrase": "He could hear me.",
        "name": "Monica",
        "season":2 ,
        "episode": 12,
        "episode_name": "The One After the Superbowl",
    },
    {
        "number": 11,
        "phrase": "If you're too afraid to be in a relationship, then don't be in one.",
        "name": "Monica",
        "season":5 ,
        "episode": 15,
        "episode_name": "The One With The Girl Who Hits Joey",
    },
    {
        "number": 12,
        "phrase": "It's never taken you more than a shower to get over a relationship.",
        "name": "Monica",
        "season":3 ,
        "episode": 17,
        "episode_name": "The One Without The Ski Trip",
    },
    {
        "number": 13,
        "phrase": "I know of two surefire ways to shut a man up. And one of them is sex.",
        "name": "Monica",
        "season":6 ,
        "episode": 23,
        "episode_name": "The One with the Ring",
    },
    {
        "number": 14,
        "phrase": "I'm not great at the advice. Can I interest you in a sarcastic comment?",
        "name": "Chandler",
        "season":8 ,
        "episode": 17,
        "episode_name": "The One with the Tea Leaves",
    },
    {
        "number": 15,
        "phrase": "I'm hopeless and awkward and desperate for love!",
        "name": "Chandler",
        "season":3 ,
        "episode": 4,
        "episode_name": "The One with the Metaphorical Tunnel",
    },
    {
        "number": 16,
        "phrase": "So it seems like this Internet thing is here to stay.",
        "name": "Chandler",
        "season":6 ,
        "episode": 15,
        "episode_name": "The One That Could Have Been: Part 1",
    },
    {
        "number": 17,
        "phrase": "If I were a guy and... Did I just say 'if I were a guy?",
        "name": "Chandler",
        "season":10 ,
        "episode": 5,
        "episode_name": "The One Where Rachel's Sister Babysits",
    },
    {
        "number": 18,
        "phrase": "I went to that tanning place your wife suggested",
        "name": "Ross",
        "season":10 ,
        "episode": 3,
        "episode_name": "The One with Ross's Tan",
    },
    {
        "number": 19,
        "phrase": "Was that place the sun?",
        "name": "Chandler",
        "season":10 ,
        "episode": 3,
        "episode_name": "The One with Ross's Tan",
    },
    {
        "number": 20,
        "phrase": "Cheese. It’s milk that you chew.",
        "name": "Chandler",
        "season":9 ,
        "episode": 11,
        "episode_name": "The One Where Rachel Goes Back to Work",
    },
    {
        "number": 21,
        "phrase": "No, Homo habilis was erect. Australopithecus was never fully erect.\nChandler: Well, maybe he was nervous.",
        "name": "Ross",
        "season":2 ,
        "episode": 15,
        "episode_name": "The One Where Ross and Rachel... You Know",
    },
    {
        "number": 22,
        "phrase": "I can handle this. 'Handle' is my middle name. Actually, 'handle' is the middle of my first name.",
        "name": "Chandler",
        "season":3 ,
        "episode": 17,
        "episode_name": "The One Without the Ski Trip",
    },
    {
        "number": 23,
        "phrase": "Until I was 25, I thought the response to 'I love you' was 'Oh, crap.",
        "name": "Chandler",
        "season":8 ,
        "episode": 17,
        "episode_name": "The One With The Tea Leaves",
    },
    {
        "number": 24,
        "phrase": "I say more dumb things before 9 A.M. than most people say all day.",
        "name": "Chandler",
        "season":4 ,
        "episode": 16,
        "episode_name": "The One With The Fake Party",
    },
    {
        "number": 25,
        "phrase": "I'm a gym member. I try to go four times a week, but I've missed the last twelve hundred times.",
        "name": "Chandler",
        "season":4 ,
        "episode": 4,
        "episode_name": "The One with the Ballroom Dancing",
    },
    {
        "number": 26,
        "phrase": "I tend to keep talking until somebody stops me.",
        "name": "Chandler",
        "season":9 ,
        "episode": 11,
        "episode_name": "The One Where Rachel Goes Back To Work",
    },
    {
        "number": 27,
        "phrase": "Oh god. Can open. Worms everywhere!",
        "name": "Chandler",
        "season":2 ,
        "episode": 16,
        "episode_name": "The One where Joey Moves Out",
    },
    {
        "number": 28,
        "phrase": "When I first meet somebody it’s usually panic, anxiety, and a great deal of sweating.",
        "name": "Chandler",
        "season":7 ,
        "episode": 18,
        "episode_name": "The One with Joey's Award",
    },
    {
        "number": 29,
        "phrase": "Alright, I took the quiz. And it turns out I do put my career before men.",
        "name": "Chandler",
        "season":3 ,
        "episode": 2,
        "episode_name": "The One Where No One's Ready",
    },
    {
        "number": 30,
        "phrase": "Oh, I know. This must be so hard. ‘Oh, no! Two women love me. They’re both gorgeous and sexy. My wallet’s too small for my fifties, and my diamond shoes are too tight!",
        "name": "Chandler",
        "season":2 ,
        "episode": 8,
        "episode_name": "The One with the List",
    },
    {
        "number": 31,
        "phrase": "Oh, man. In my next life, I’m coming back as a toilet brush!",
        "name": "Chandler",
        "season":1 ,
        "episode": 14,
        "episode_name": "The One with the Candy Hearts",
    },
    {
        "number": 32,
        "phrase": "Offering people gum is not cooking.",
        "name": "Chandler",
        "season":6 ,
        "episode": 9,
        "episode_name": "The One Where Ross Got High",
    },
    {
        "number": 33,
        "phrase": "You're a door. You only like knock-knock jokes.",
        "name": "Chandler",
        "season":9 ,
        "episode": 6,
        "episode_name": "The One with the Male Nanny",
    },
    {
        "number": 34,
        "phrase": "This parachute is a knapsack!",
        "name": "Chandler",
        "season":1 ,
        "episode": 23,
        "episode_name": "The One With The Birth",
    },
    {
        "number": 35,
        "phrase": "What must it be like not to be crippled by fear and self-loathing?",
        "name": "Chandler",
        "season":10 ,
        "episode": 3,
        "episode_name": "The One with Ross's Tan",
    },
    {
        "number": 36,
        "phrase": "It’s always better to lie than to have the complicated discussion.",
        "name": "Chandler",
        "season":9 ,
        "episode": 9,
        "episode_name": "The One with Rachel's Phone Number",
    },
    {
        "number": 37,
        "phrase": "I’m glad we’re having a rehearsal dinner, I rarely practice my meals before I eat.",
        "name": "Chandler",
        "season":10 ,
        "episode": 12,
        "episode_name": "The One with Phoebe's Wedding",
    },
    {
        "number": 38,
        "phrase": "If you’re not careful, you might not get married at all this year.",
        "name": "Chandler",
        "season":6 ,
        "episode": 24,
        "episode_name": "The One with the Proposal: Part 1",
    },
    {
        "number": 39,
        "phrase": "I think I can safely say that we all have family issues, work, and/or are sick.",
        "name": "Chandler",
        "season":9 ,
        "episode": 22,
        "episode_name": "The One With the Donor",
    },
    {
        "number": 40,
        "phrase": "Oh you like that? You should hear my phone number.",
        "name": "Phoebe",
        "season":7 ,
        "episode": 4,
        "episode_name": "The One with Rachel's Assistant",
    },
    {
        "number": 41,
        "phrase": "Come on, Ross, you’re a paleontologist. Dig a little deeper.",
        "name": "Phoebe",
        "season":6 ,
        "episode": 23,
        "episode_name": "The One with the Ring",
    },
    {
        "number": 42,
        "phrase": "Well, if she isn’t (dead), cremating her was a big mistake.",
        "name": "Phoebe",
        "season":5 ,
        "episode": 13,
        "episode_name": "The One with Joey's Bag",
    },
    {
        "number": 43,
        "phrase": "I’m a pacifist. But when the revolution comes, I’ll destroy all of you.",
        "name": "Phoebe",
        "season":5 ,
        "episode": 20,
        "episode_name": "The One with the Ride Along",
    },
    {
        "number": 44,
        "phrase": "13 bathrooms in this place, I threw up in a coat closet.",
        "name": "Phoebe",
        "season":9 ,
        "episode": 7,
        "episode_name": "The One With Ross's Inappropriate Song",
    },
    {
        "number": 45,
        "phrase": "It's so exhausting, waiting for death.",
        "name": "Phoebe",
        "season":6,
        "episode": 4,
        "episode_name": "The One Where Joey Loses His Insurance",
    },
    {
        "number": 46,
        "phrase": "Oh, my God, a woman flirting with a single man? We must alert the church elders!",
        "name": "Phoebe",
        "season":8 ,
        "episode": 21,
        "episode_name": "The One with the Cooking Class",
    },
    {
        "number": 47,
        "phrase": "This is the nicest kitchen... The refrigerator told me to have a great day.",
        "name": "Phoebe",
        "season":3 ,
        "episode": 23,
        "episode_name": "The One with Ross's Thing",
    },
    {
        "number": 48,
        "phrase": "I don't even have a 'pla.",
        "name": "Phoebe",
        "season":1 ,
        "episode": 4,
        "episode_name": "The One with George Stephanopoulos",
    },
    {
        "number": 49,
        "phrase": "Something is wrong with the left phalange.",
        "name": "Phoebe",
        "season":10 ,
        "episode": 17,
        "episode_name": "The Last One: Part 1",
    },
    {
        "number": 50,
        "phrase": "Didn’t you ever run so fast you thought your legs were gonna fall off, you know, like when you were running toward the swings or running away from Satan?",
        "name": "Phoebe",
        "season":6 ,
        "episode": 7,
        "episode_name": "The One Where Phoebe Runs",
    },
    {
        "number": 51,
        "phrase": "They don't know that we know they know we know.",
        "name": "Phoebe",
        "season":5 ,
        "episode": 14,
        "episode_name": "The One Where Everybody Finds Out",
    },
    {
        "number":52 ,
        "phrase": "Princess Consuela Bananahammock.",
        "name": "Phoebe",
        "season":10 ,
        "episode": 14,
        "episode_name": "The One with Princess Consuela",
    },
    {
        "number": 53,
        "phrase": "I am against innocent trees being cut down in their prime and their corpses grotesquely dressed in, like, tinsel and twinkly lights.",
        "name": "Phoebe",
        "season":3 ,
        "episode": 10,
        "episode_name": "The One Where Rachel Quits",
    },
    {
        "number": 54,
        "phrase": "Everybody looks so happy. I hate that.",
        "name": "Phoebe",
        "season":1 ,
        "episode": 10,
        "episode_name": "The One With the Monkey",
    },
    {
        "number": 55,
        "phrase": "I’m very wise, I know.",
        "name": "Phoebe",
        "season":7 ,
        "episode": 11,
        "episode_name": "The One with All the Cheesecakes",
    },
    {
        "number": 56,
        "phrase": "You love divorce so much, you’re probably gonna marry it — and then it won’t work out, so you’re gonna have to divorce it.",
        "name": "Phoebe",
        "season":4 ,
        "episode": 15,
        "episode_name": "The One with All the Rugby",
    },
    {
        "number": 57,
        "phrase": "See? He's her lobster!",
        "name": "Phoebe",
        "season":2 ,
        "episode": 14,
        "episode_name": "The One with the Prom Video",
    },
    {
        "number": 58,
        "phrase": "You should see me when I actually... Oh actually, no, I look good.",
        "name": "Phoebe",
        "season":9 ,
        "episode": 6,
        "episode_name": "The One with the Male Nanny",
    },
    {
        "number": 59,
        "phrase": "I think the most romantic song is the one that Elton John wrote for that guy from ‘Who’s the Boss?’… You know, ‘Hold me closer, Tony Danza.",
        "name": "Phoebe",
        "season":3 ,
        "episode": 1,
        "episode_name": "The One with the Princess Leia Fantasy",
    },
    {
        "number": 60,
        "phrase": "I wish I could, but I don't want to.",
        "name": "Phoebe",
        "season":1 ,
        "episode": 1,
        "episode_name": "The One Where Monica Gets a Roommate",
    },
    {
        "number": 61,
        "phrase": "I’m a lady, Monica. I don’t kiss and tell. But this hickey speaks for itself.",
        "name": "Phoebe",
        "season":7 ,
        "episode": 18,
        "episode_name": "The One with Joey's Award",
    },
    {
        "number": 62,
        "phrase": "Are you in there, little fetus? In nine months, will you greet us? I will... buy you some Adidas.”",
        "name": "Phoebe",
        "season":4 ,
        "episode": 12,
        "episode_name": "The One with the Embryos",
    },
    {
        "number": 63,
        "phrase": "If you want to receive emails about my upcoming shows, please give me money so I can buy a computer.",
        "name": "Phoebe",
        "season":6 ,
        "episode": 3,
        "episode_name": "The One with Ross's Denial",
    },
    {
        "number": 64,
        "phrase": "Smelly cat, smelly cat, what are they feeding you? Smelly cat, smelly cat, it’s not your fault.",
        "name": "Phoebe",
        "season":2 ,
        "episode": 6,
        "episode_name": "The One with the Baby on the Bus",
    },
    {
        "number": 65,
        "phrase": "Isn't that just kick-you-in-the-crotch, spit-on-your-neck fantastic?",
        "name": "Rachel",
        "season":2 ,
        "episode": 1,
        "episode_name": "The One with Ross's New Girlfriend",
    },
    {
        "number": 66,
        "phrase": "Why can’t parents just stay parents? You know? Why do they have to become people?",
        "name": "Rachel",
        "season":1 ,
        "episode": 13,
        "episode_name": "The One With The Boobies",
    },
    {
        "number": 67,
        "phrase": "We are dessert stealers. We are living outside the law.",
        "name": "Rachel",
        "season":7 ,
        "episode": 11,
        "episode_name": "The One with All the Cheesecakes",
    },
    {
        "number": 68,
        "phrase": "That’s a great story. Tell it while you’re getting me some iced tea.",
        "name": "Rachel",
        "season":8 ,
        "episode": 22,
        "episode_name": "The One Where Rachel Is Late",
    },
    {
        "number": 69,
        "phrase": "He's so pretty, I want to cry.",
        "name": "Rachel",
        "season":7 ,
        "episode": 4,
        "episode_name": "The One With Rachel's Assistant",
    },
    {
        "number":70 ,
        "phrase": "Oh my God. I’ve become my father. I’ve been trying so hard not to become my mother, I didn’t see this coming.",
        "name": "Rachel",
        "season":2 ,
        "episode": 7,
        "episode_name": "The One Where Ross Finds Out",
    },
    {
        "number": 71,
        "phrase": " Well, what if I don’t want to be a shoe? What if I wanna be a purse or a hat?",
        "name": "Rachel",
        "season":1 ,
        "episode": 1,
        "episode_name": "The One Where Monica Gets a Roommate",
    },
    {
        "number": 72,
        "phrase": "No uterus, no opinion.",
        "name": "Rachel",
        "season":8 ,
        "episode": 14,
        "episode_name": "he One with the Secret Closet",
    },
    {
        "number": 73,
        "phrase": "It tastes like feet.",
        "name": "Ross",
        "season":6 ,
        "episode": 9,
        "episode_name": "The One Where Ross Got High",
    },
    {
        "number": 74,
        "phrase": "Today, it’s like there’s rock bottom, then 50 feet of crap, then me.",
        "name": "Rachel",
        "season":2 ,
        "episode": 1,
        "episode_name": "The One With Ross's New Girlfriend",
    },
    {
        "number": 75,
        "phrase": "Does this look like something the girlfriend of a paleontologist would wear?",
        "name": "Rachel",
        "season":3 ,
        "episode": 2,
        "episode_name": "he One Where No One's Ready",
    },
    {
        "number": 76,
        "phrase": "Ross! We broke up two years ago. You’ve been married since then. I think it’s okay that we see other people.",
        "name": "Rachel",
        "season":5 ,
        "episode": 19,
        "episode_name": "The One Where Ross Can't Flirt",
    },
    {
        "number": 77,
        "phrase": "Oh I'm sorry, did my back hurt your knife?",
        "name": "Rachel",
        "season":2 ,
        "episode": 2,
        "episode_name": "The One with the Breast Milk",
    },
    {
        "number": 78,
        "phrase": "You know what? I just shouldn’t be allowed to make decisions anymore.",
        "name": "Rachel",
        "season":5 ,
        "episode": 2,
        "episode_name": "The One with All the Kissing",
    },
    {
        "number": 79,
        "phrase": "I’m gonna go get one of those job things.",
        "name": "Rachel",
        "season":1 ,
        "episode": 13,
        "episode_name": "The One With The Boobies",
    },
    {
        "number": 80,
        "phrase": "Who’s FICA? Why’s he getting all my money?",
        "name": "Rachel",
        "season":1 ,
        "episode": 4,
        "episode_name": "The One with George Stephanopoulos",
    },
    {
        "number": 81,
        "phrase": "I hope it's still funny when you're in hell.",
        "name": "Rachel",
        "season":3 ,
        "episode": 8,
        "episode_name": "The One With The Giant Poking Device",
    },
    {
        "number": 82,
        "phrase": "Oh, that's okay, girls tend to not like me.",
        "name": "Rachel",
        "season":10 ,
        "episode": 2,
        "episode_name": "The One Where Ross Is Fine",
    },
    {
        "number": 83,
        "phrase": "Oh, are you setting Ross up with someone? Does she have a wedding dress?",
        "name": "Rachel",
        "season":6 ,
        "episode": 8,
        "episode_name": "The One with Ross' Teeth",
    },
    {
        "number": 84,
        "phrase": "Food? Oh, give me.",
        "name": "Joey",
        "season":7 ,
        "episode": 17,
        "episode_name": "The One with the Cheap Wedding Dress",
    },
    {
        "number": 85,
        "phrase": "Well, maybe I don’t need your money. Wait, wait! I said, ‘Maybe.",
        "name": "Rachel",
        "season":1 ,
        "episode": 1,
        "episode_name": "The One Where Monica Gets a Roommate",
    },
    {
        "number": 86,
        "phrase": "These are just feelings. They’ll go away.",
        "name": "Joey",
        "season":8 ,
        "episode": 16,
        "episode_name": "The One Where Joey Tells Rachel",
    },
    {
        "number": 87,
        "phrase": "Here come the meat sweats.",
        "name": "Joey",
        "season":8 ,
        "episode": 9,
        "episode_name": "The One With the Rumor",
    },
    {
        "number": 88,
        "phrase": "I look a woman up and down and say, 'How you doin?",
        "name": "Joey",
        "season":4 ,
        "episode": 13,
        "episode_name": "The One with Rachel's Crush",
    },
    {
        "number": 89,
        "phrase": "I’m fine.",
        "name": "Ross",
        "season":10 ,
        "episode": 2,
        "episode_name": "The One Where Ross Is Fine",
    },
    {
        "number": 90,
        "phrase": "Hey, Ross, I got a science question: If the Homo sapiens were, in fact, HOMO sapiens...is that why they're extinct?",
        "name": "Joey",
        "season":3 ,
        "episode": 8,
        "episode_name": "The One With The Giant Poking Device",
    },
    {
        "number": 91,
        "phrase": "No, I don’t! To hell with her! She left me!",
        "name": "Ross",
        "season":1 ,
        "episode": 1,
        "episode_name": "The One Where Monica Gets a Roommate",
    },
    {
        "number": 92,
        "phrase": "If he doesn’t like you, this is all a moo point.\nYeah. It’s like a cow’s opinion. It just doesn’t matter. It’s moo.",
        "name": "Joey",
        "season":7 ,
        "episode": 8,
        "episode_name": "The One Where Chandler Doesn't Like Dogs",
    },
    {
        "number": 93,
        "phrase": "Well, the fridge broke, so I had to eat everything",
        "name": "Joey",
        "season":6 ,
        "episode": 19,
        "episode_name": "The One With Joey's Fridge",
    },
    {
        "number": 94,
        "phrase": "Over the line? You’re so far past the line that you can’t even see the line! The line is a dot to you!",
        "name": "Joey",
        "season":4 ,
        "episode": 7,
        "episode_name": "The One Where Chandler Crosses the Line",
    },
    {
        "number": 95,
        "phrase": "You can’t just give up! Is that what a dinosaur would do?",
        "name": "Joey",
        "season":10 ,
        "episode": 17,
        "episode_name": "The Last One",
    },
    {
        "number": 96,
        "phrase": "You don’t own a TV? What’s all your furniture pointed at?",
        "name": "Joey",
        "season":9 ,
        "episode": 23,
        "episode_name": "The One in Barbados: Part 1",
    },
    {
        "number": 97,
        "phrase": "I like it. What’s not to like? Custard? Good. Jam? Good. Meat? Good.",
        "name": "Joey",
        "season":6 ,
        "episode": 9,
        "episode_name": "The One Where Ross Got High",
    },
    {
        "number": 98,
        "phrase": "Okay. So I’m out four thousand dollars and nobody’s boobs are getting any bigger?",
        "name": "Joey",
        "season":9 ,
        "episode": 16,
        "episode_name": "he One With The Boob Job",
    },
    {
        "number": 99,
        "phrase": "Look at me! I’m Chandler! Could I be wearing any more clothes?",
        "name": "Joey",
        "season":3 ,
        "episode": 2,
        "episode_name": "The One Where No One's Ready",
    },
    {
        "number": 100,
        "phrase": "That’s right, I stepped up! She’s my friend and she needed help. If I had to, I’d pee on any one of you!",
        "name": "Joey",
        "season":4 ,
        "episode": 1,
        "episode_name": "The One with the Jellyfish",
    },
    {
        "number": 101,
        "phrase": "Man, I’m starving. What was I thinking at dinner? ‘Do you want soup or salad?’ Both. Always order both.",
        "name": "Joey",
        "season":7 ,
        "episode": 12,
        "episode_name": "The One Where They're Up All Night",
    },
    {
        "number": 102,
        "phrase": "Ah, humor based on my pain. Ah, ha, ha.",
        "name": "Ross",
        "season":6 ,
        "episode": 17,
        "episode_name": "The One With the Unagi",
    },
    {
        "number": 103,
        "phrase": "Because my wife's a lesbian... And I'm not one.",
        "name": "Ross",
        "season":3 ,
        "episode": 6,
        "episode_name": "The One with the Flashback",
    },
    {
        "number": 104,
        "phrase": "Look, it's the artist formerly known as Chandler.",
        "name": "Ross",
        "season":2 ,
        "episode": 20,
        "episode_name": "The One Where Old Yeller Dies",
    },
    {
        "number": 105,
        "phrase": "Huh. That’s a really pretty name for an industrial solvent.",
        "name": "Ross",
        "season":8 ,
        "episode": 13,
        "episode_name": "The One Where Chandler Takes a Bath",
    },
    {
        "number": 106,
        "phrase": "You-you-you... You threw my sandwich away... My sandwich? MY SANDWICH?!!",
        "name": "Ross",
        "season":5 ,
        "episode": 9,
        "episode_name": "The One with Ross's Sandwich",
    },
    {
        "number": 107,
        "phrase": "Ah, love. L-O-V-E love. ‘L’ is for life. I mean what is life without love?",
        "name": "Ross",
        "season":10 ,
        "episode": 2,
        "episode_name": "The One Where Ross Is Fine",
    },
    {
        "number": 108,
        "phrase": "Unagi is a total state of awareness.",
        "name": "Ross",
        "season":6 ,
        "episode": 17,
        "episode_name": "The One With the Unagi",
    },
    {
        "number": 109,
        "phrase": "I tell you, when I actually die, some people are gonna get seriously haunted.",
        "name": "Ross",
        "season":9 ,
        "episode": 17,
        "episode_name": "The One With the Memorial Service",
    },
    {
        "number": 110,
        "phrase": "You can see the moonlight bouncing off her head!",
        "name": "Ross",
        "season":3 ,
        "episode": 25,
        "episode_name": "The One at the Beach",
    },
    {
        "number": 111,
        "phrase": "A loser you did it with 298 times!",
        "name": "Ross",
        "season":5 ,
        "episode": 16,
        "episode_name": "The One With the Cop",
    },
    {
        "number": 112,
        "phrase": "I'd really rather not answer that, right now. I'm still carrying a little holiday weight.",
        "name": "Ross",
        "season":7 ,
        "episode": 12,
        "episode_name": "The One Where They're Up All Night",
    },
    {
        "number": 113,
        "phrase": "I grew up in a house with Monica, OK. If you didn't eat fast, you didn't eat.",
        "name": "Ross",
        "season":8 ,
        "episode": 3,
        "episode_name": "The One Where Rachel Tells",
    },
    {
        "number": 114,
        "phrase": "Emotional hell.",
        "name": "Ross",
        "season":2 ,
        "episode": 14,
        "episode_name": "The One with the Prom Video",
    },
    {
        "number": 115,
        "phrase": "You're right. Let's cool off, get some frozen yogurt.",
        "name": "Ross",
        "season":3 ,
        "episode": 16,
        "episode_name": "The One with the Morning After",
    },
    {
        "number": 116,
        "phrase": "Um, excuse me; I don't remember you making any sperm.",
        "name": "Ross",
        "season":1 ,
        "episode": 2,
        "episode_name": "The One with the Sonogram at the End",
    },
    {
        "number": 117,
        "phrase": "Y'know what? I'm gonna go out on a limb and say no divorces in '99!",
        "name": "Ross",
        "season":5 ,
        "episode": 11,
        "episode_name": "The One with All the Resolutions",
    },
    {
        "number": 118,
        "phrase": "I am this close to tugging on my testicles again.",
        "name": "Ross",
        "season":10 ,
        "episode": 4,
        "episode_name": "The One With the Cake",
    },
    {
        "number": 119,
        "phrase": "You and those vegetables have, uh... real thing going, huh?",
        "name": "Ross",
        "season":5 ,
        "episode": 19,
        "episode_name": "The One Where Ross Can't Flirt",
    },
    {
        "number": 120,
        "phrase": "Only by achieving true unagi can you be prepared for any danger that may befall you.",
        "name": "Ross",
        "season":6 ,
        "episode": 17,
        "episode_name": "The One With the Unagi",
    },
    {
        "number": 121,
        "phrase": "You’re over me? When were you... under me?",
        "name": "Ross",
        "season":2 ,
        "episode": 7,
        "episode_name": "The One Where Ross Finds Out",
    },
    {
        "number": 122,
        "phrase": "Pivot! Pivot! Pivot!",
        "name": "Ross",
        "season":5 ,
        "episode": 16,
        "episode_name": "The One with the Cop",
    },
    {
        "number": 123,
        "phrase": "In Vegas. I was so drunk, I could've married Joey.",
        "name": "Ross",
        "season":6 ,
        "episode": 2,
        "episode_name": "The One Where Ross Hugs Rachel",
    },
    {
        "number": 124,
        "phrase": "I'm the holiday armadillo!",
        "name": "Ross",
        "season":7 ,
        "episode":10,
        "episode_name": "The One with the Holiday Armadillo",
    },
    {
        "number": 125,
        "phrase": "Get off my sister!",
        "name": "Ross",
        "season":5 ,
        "episode": 14,
        "episode_name": "The One Where Everybody Finds Out",
    },
  {
        "number": 126,
        "phrase": "I hope everyone likes Mexican food because I’m making FAJITAS!",
        "name": "Ross",
        "season":10 ,
        "episode": 2,
        "episode_name": "The One Where Ross Is Fine",
    },
  {
        "number": 127,
        "phrase": "A no-sex pact, huh? I seem to have one of those going with every woman in America.",
        "name": "Ross",
        "season":7 ,
        "episode": 19,
        "episode_name": "The One With Ross And Monica's Cousin",
    },
  {
        "number": 128,
        "phrase": "If you're gonna do something wrong, do it right!",
        "name": "Joey",
        "season":4 ,
        "episode": 16,
        "episode_name": "The One With the Fake Party",
    },

  
]
